version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    #container_name: mongodb
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: max
      #MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mong.env

  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider


    #build: ./backend
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#      args:
#        some-arg: 1


volumes:
  data:
  logs:
